Repository apache/skywalking-go, pull requests merged in 2023-04, with the labels that each got.

#2 Update missing CI
  .github/workflows/skywalking-go.yaml
Labels: chore

#1 Update star badge.
  README.md
Labels: chore

#7 Update tools name and missing `go.sum`
  Makefile
  go.sum
  tools/go-agent/Makefile
  tools/go-agent/cmd/helper.go
  tools/go-agent/cmd/main.go
  tools/go-agent/go.mod
  tools/go-agent/go.sum
  tools/go-agent/instrument/agentcore/instrument.go
  tools/go-agent/instrument/api/flags.go
  tools/go-agent/instrument/api/instrument.go
  tools/go-agent/instrument/instrument.go
  tools/go-agent/instrument/runtime/instrument.go
  tools/go-agent/tools/dst.go
  tools/go-agent/tools/enhancement.go
  tools/go-agent/tools/files.go
  tools/go-agent/tools/flags.go
  tools/go-agent/tools/logger.go
  tools/go-agent/tools/templetes.go
Labels: enhancement

#14 Update documentation for official website
  README.md
  docs/README.md
  docs/menu.yml
Labels: documentation

#15 Setup plugin tests and add gin plugin test
  .github/workflows/plugin-tests.yaml
  .gitignore
  test/plugins/Makefile
  test/plugins/run.sh
  test/plugins/runner-helper/context.go
  test/plugins/runner-helper/go.mod
  test/plugins/runner-helper/go.sum
  test/plugins/runner-helper/main.go
  test/plugins/runner-helper/templates/docker-compose.tpl
  test/plugins/runner-helper/templates/dockerfile.tpl
  test/plugins/runner-helper/templates/render.go
  test/plugins/runner-helper/templates/scenarios.tpl
  test/plugins/runner-helper/templates/validator.tpl
  test/plugins/scenarios/gin/bin/startup.sh
  test/plugins/scenarios/gin/config/excepted.yml
  test/plugins/scenarios/gin/go.mod
  test/plugins/scenarios/gin/go.sum
  test/plugins/scenarios/gin/main.go
  test/plugins/scenarios/gin/plugin.yml
  test/plugins/validator/Dockerfile
  tools/go-agent/cmd/main.go
  tools/go-agent/instrument/instrument.go
  tools/go-agent/instrument/plugins/instrument.go
Labels: enhancement

#17 Change to using workspace
  .licenserc.yaml
  Makefile
  go.work
  go.work.sum
  plugins/core/go.mod
  plugins/core/go.sum
  plugins/core/propagation_test.go
  plugins/core/tracer.go
  plugins/core/tracer_state.go
  plugins/core/tracer_test.go
  plugins/core/tracing.go
  plugins/ginv2/go.mod
  plugins/ginv2/go.sum
  plugins/ginv2/intercepter.go
  plugins/ginv2/intercepter_test.go
  plugins/http/go.mod
  plugins/http/go.sum
  plugins/http/intercepter_test.go
  test/plugins/run.sh
  test/plugins/runner-helper/context.go
  test/plugins/runner-helper/go.mod
  test/plugins/runner-helper/go.sum
  test/plugins/runner-helper/main.go
  test/plugins/runner-helper/templates/docker-compose.tpl
  test/plugins/runner-helper/templates/dockerfile.tpl
  test/plugins/scenarios/gin/go.mod
  test/plugins/scenarios/gin/go.sum
  tools/go-agent/go.mod
  tools/go-agent/go.sum
  tools/go-agent/instrument/agentcore/instrument.go
  tools/go-agent/instrument/plugins/instrument.go
  tools/go-agent/tools/enhancement.go
  tools/go-agent/tools/types.go
Labels: enhancement

#20 Polish menu
  docs/en/agent/support-plugins.md
  docs/menu.yml
Labels: documentation
