Repository apache/skywalking-go, pull requests merged in 2023-10, with the labels that each got.

#102 doc: correct the image name to be apache/skywalking-go
  docs/en/setup/docker.md
Labels: documentation

#122 feat: update Makefile to support build arm64 platform
  tools/go-agent/Makefile
Labels: enhancement

#125 Fix Docker image not supporting the `arm64` platform
  CHANGES.md
  Dockerfile
Labels: bug

#126 Begin v0.4.0 version
  CHANGES.md
Labels: chore

#132 Update the release documentation for the toolkit
  docs/en/development-and-contribution/how-to-release.md
Labels: documentation

#131 fix: Update toolkit-trace.md
  docs/en/advanced-features/manual-apis/toolkit-trace.md
Labels: documentation

#149 Disable dependency Bot Pull Requests
  .asf.yaml
Labels: chore

#133 feature: add support for fiber
  .github/workflows/plugin-tests.yaml
  CHANGES.md
  docs/en/agent/support-plugins.md
  go.sum
  go.work
  plugins/fiber/go.mod
  plugins/fiber/go.sum
  plugins/fiber/instrument.go
  plugins/fiber/intercepter.go
  test/plugins/scenarios/fiber/bin/startup.sh
  test/plugins/scenarios/fiber/config/excepted.yml
  test/plugins/scenarios/fiber/go.mod
  test/plugins/scenarios/fiber/go.sum
  test/plugins/scenarios/fiber/main.go
  test/plugins/scenarios/fiber/plugin.yml
  tools/go-agent/instrument/plugins/register.go
Labels: duplicate, enhancement
