Repository apache/skywalking-go, pull requests merged in 2023-05, with the labels that each got.

#21 Add Performance test case
  docs/en/agent/performance-tests.md
  go.work
  go.work.sum
  plugins/core/propagating.go
  plugins/core/span_tracing.go
  plugins/http/intercepter.go
  test/benchmark-codebase/consumer/go.mod
  test/benchmark-codebase/consumer/go.sum
  test/benchmark-codebase/consumer/main.go
  test/benchmark-codebase/provider/go.mod
  test/benchmark-codebase/provider/go.sum
  test/benchmark-codebase/provider/main.go
Labels: documentation, enhancement

#24 Add explanation for extra payload
  docs/en/agent/performance-tests.md
Labels: documentation

#25 Move the gRPC reporter to the agent tool for generate
  agent/core/compile.go
  agent/core/tracing/compile.go
  agent/reporter/imports.go
  go.mod
  go.sum
  go.work.sum
  imports.go
  plugins/core/reporter/api.go
  plugins/core/reporter/config_discovery.go
  plugins/core/reporter/grpc/grpc.go
  plugins/core/reporter/grpc/grpc_opts_enhance.go
  plugins/core/sampler.go
  plugins/core/span_default.go
  plugins/core/span_tracing.go
  plugins/core/test_base.go
  plugins/core/tracer.go
  plugins/core/tracer_test.go
  plugins/core/tracing.go
  reporter/doc.go
  reporter/grpc_opts.go
  reporter/imports.go
  reporter/reporter.go
  test/plugins/runner-helper/templates/dockerfile.tpl
  test/plugins/scenarios/gin/go.mod
  test/plugins/scenarios/gin/go.sum
  tools/go-agent/instrument/agentcore/instrument.go
  tools/go-agent/instrument/plugins/rewrite/rewrite.go
  tools/go-agent/instrument/reporter/instrument.go
  tools/go-agent/tools/copy.go
  tools/go-agent/tools/dst.go
Labels: enhancement

#29 Split the build documentation into development version and user setup version
  docs/en/development-and-contribution/build-and-use-agent.md
  docs/en/setup/gobuild.md
  docs/menu.yml
Labels: documentation

#30 Skip tracing if gRPC connection is down
  plugins/core/reporter/api.go
  plugins/core/reporter/grpc/grpc.go
  plugins/core/test_base.go
  plugins/core/tracer.go
  plugins/core/tracing.go
  plugins/core/tracing_test.go
  tools/go-agent/tools/dst.go
Labels: enhancement

#28 Fix container name inconsistency in file scenarios.tpl
  test/plugins/runner-helper/templates/scenarios.tpl
Labels: testing

#33 Support dubbo plugin
  .github/workflows/plugin-tests.yaml
  .gitignore
  Makefile
  docs/en/agent/support-plugins.md
  go.mod
  go.sum
  go.work
  go.work.sum
  plugins/core/go.mod
  plugins/core/go.sum
  plugins/dubbo/filter/graceful_shutdown/client_intercepter.go
  plugins/dubbo/filter/graceful_shutdown/server_intercepter.go
  plugins/dubbo/go.mod
  plugins/dubbo/go.sum
  plugins/dubbo/instrument.go
  plugins/ginv2/go.mod
  plugins/ginv2/go.sum
  plugins/ginv2/instrument.go
  plugins/http/go.mod
  plugins/http/go.sum
  plugins/http/instrument.go
  test/benchmark-codebase/consumer/go.mod
  test/benchmark-codebase/consumer/go.sum
  test/benchmark-codebase/provider/go.mod
  test/benchmark-codebase/provider/go.sum
  test/plugins/run.sh
  test/plugins/runner-helper/go.mod
  test/plugins/runner-helper/go.sum
  test/plugins/scenarios/dubbo/api/api.proto
  test/plugins/scenarios/dubbo/bin/startup.sh
  test/plugins/scenarios/dubbo/config/excepted.yml
  test/plugins/scenarios/dubbo/go-client/cmd/client.go
  test/plugins/scenarios/dubbo/go-client/conf/dubbogo.yaml
  test/plugins/scenarios/dubbo/go-server/cmd/server.go
  test/plugins/scenarios/dubbo/go-server/conf/dubbogo.yaml
  test/plugins/scenarios/dubbo/go.mod
  test/plugins/scenarios/dubbo/go.sum
  test/plugins/scenarios/dubbo/plugin.yml
  test/plugins/scenarios/gin/go.mod
  test/plugins/scenarios/gin/go.sum
  test/plugins/scenarios/http/go.mod
  test/plugins/scenarios/http/go.sum
  tools/go-agent/Makefile
  tools/go-agent/go.mod
  tools/go-agent/go.sum
  tools/go-agent/instrument/logger/instrument.go
  tools/go-agent/instrument/plugins/enhance_method.go
  tools/go-agent/instrument/plugins/instrument.go
  tools/go-agent/instrument/plugins/register.go
  tools/go-agent/instrument/plugins/rewrite/context.go
  tools/go-agent/tools/dst.go
Labels: enhancement

#40 fix custome file do not take effect (#10821)
  tools/go-agent/config/loader.go
  tools/go-agent/config/loader_test.go
  tools/go-agent/config/testdata/agent.yaml
Labels: bug

#42 Add multiple platform and go version build check
  .github/workflows/skywalking-go.yaml
Labels: testing

#45 Refactor the global ID generator
  plugins/core/context.go
  plugins/core/id.go
  plugins/core/id_test.go
  plugins/core/span_tracing.go
  plugins/core/tool.go
  plugins/core/tracing.go
  tools/go-agent/instrument/agentcore/instrument.go
  tools/go-agent/instrument/consts/operator.go
  tools/go-agent/instrument/runtime/instrument.go
Labels: enhancement

#47 Add async span API
  docs/en/development-and-contribution/development-guide.md
  plugins/core/span_default.go
  plugins/core/span_noop.go
  plugins/core/span_tracing.go
  plugins/core/tracing.go
  plugins/core/tracing/api.go
  plugins/core/tracing/bridge.go
  plugins/core/tracing/span.go
  plugins/core/tracing_test.go
  tools/go-agent/instrument/plugins/rewrite/type.go
Labels: enhancement
