Repository apache/skywalking-go, pull requests merged in 2023-08, with the labels that each got.

#87 Add Mux framework support
  .github/workflows/plugin-tests.yaml
  CHANGES.md
  docs/en/agent/support-plugins.md
  go.work
  plugins/mux/go.mod
  plugins/mux/go.sum
  plugins/mux/instrument.go
  plugins/mux/match_interceptor.go
  plugins/mux/serve_interceptor.go
  plugins/mux/structures.go
  test/plugins/scenarios/kratosv2/config/excepted.yml
  test/plugins/scenarios/mux/bin/startup.sh
  test/plugins/scenarios/mux/config/excepted.yml
  test/plugins/scenarios/mux/go.mod
  test/plugins/scenarios/mux/go.sum
  test/plugins/scenarios/mux/main.go
  test/plugins/scenarios/mux/plugin.yml
  tools/go-agent/instrument/plugins/register.go
Labels: plugin

#95 fix: helper message typo
  tools/go-agent/cmd/helper.go
Labels: documentation

#98 test: add a compitable version function
  tools/go-agent/cmd/injector.go
  tools/go-agent/cmd/injector_test.go
Labels: enhancement
