Repository apache/skywalking-go, pull requests merged in 2023-06, with the labels that each got.

#57 Enhance the plugin rewrite ability
  CHANGES.md
  tools/go-agent/instrument/plugins/rewrite/context.go
  tools/go-agent/instrument/plugins/rewrite/func.go
Labels: enhancement

#55 Add support for go-redis
  .github/workflows/plugin-tests.yaml
  CHANGES.md
  docs/en/agent/support-plugins.md
  go.work
  plugins/core/tracing/span.go
  plugins/go-redisv9/go.mod
  plugins/go-redisv9/go.sum
  plugins/go-redisv9/hook.go
  plugins/go-redisv9/instrument.go
  plugins/go-redisv9/intercepter.go
  plugins/go-redisv9/op_type.go
  test/plugins/scenarios/go-redisv9/bin/startup.sh
  test/plugins/scenarios/go-redisv9/config/excepted.yml
  test/plugins/scenarios/go-redisv9/go.mod
  test/plugins/scenarios/go-redisv9/go.sum
  test/plugins/scenarios/go-redisv9/main.go
  test/plugins/scenarios/go-redisv9/plugin.yml
  tools/go-agent/instrument/plugins/register.go
Labels: enhancement, plugin

#56 Support running e2e tests on MacOS
  .github/workflows/plugin-tests.yaml
  test/plugins/run.sh
Labels: enhancement

#58 Support inject the skywalking-go into project through agent
  CHANGES.md
  docs/en/setup/gobuild.md
  tools/go-agent/cmd/helper.go
  tools/go-agent/cmd/injector.go
  tools/go-agent/cmd/injector_test.go
  tools/go-agent/cmd/main.go
  tools/go-agent/cmd/testdata/entry/test.go
  tools/go-agent/cmd/testdata/imports/test.go
  tools/go-agent/cmd/testdata/noimports/test.go
Labels: enhancement

#61 Fix throw panic when log the tracing context before agent core initialized
  CHANGES.md
  tools/go-agent/instrument/logger/context.go
Labels: bug

#64 bug: Fix plugin version matcher to support capital letters in module paths and versions
  CHANGES.md
  tools/go-agent/instrument/plugins/instrument.go
  tools/go-agent/instrument/plugins/instrument_test.go
Labels: bug
