Repository apache/skywalking-go, pull requests merged in 2023-12, with the labels that each got.

#155 bugfix:forget to set metrics & log ch as well
  CHANGES.md
  plugins/core/reporter/grpc/grpc_opts_enhance.go
Labels: bug

#157 Fix macOS CI Testing
  .github/workflows/plugin-tests.yaml
Labels: chore

#156 Changing intercept point for gin, make sure interfaces could be group…
  CHANGES.md
  plugins/gin/instrument.go
  plugins/gin/intercepter.go
  plugins/gin/intercepter_test.go
Labels: enhancement, plugin
