Repository apache/skywalking-go, pull requests merged in 2024-02, with the labels that each got.

#167 fix lost trace when multi middleware handlerFunc
  CHANGES.md
  plugins/gin/intercepter.go
  plugins/gin/structures.go
Labels: bug, plugin

#170 feature: add golang 1.21, 1.22 compatibility for docker image
  Makefile
Labels: enhancement

#169 feature: add support for rocketMQ
  .github/workflows/plugin-tests.yaml
  CHANGES.md
  docs/en/agent/support-plugins.md
  go.work
  plugins/core/tracing/span.go
  plugins/rocketmq/consumer/consumer.go
  plugins/rocketmq/consumer/consumer_status.go
  plugins/rocketmq/consumer/structures.go
  plugins/rocketmq/go.mod
  plugins/rocketmq/go.sum
  plugins/rocketmq/instrument.go
  plugins/rocketmq/producer/async_producer.go
  plugins/rocketmq/producer/general_producer.go
  plugins/rocketmq/producer/send_one_way.go
  plugins/rocketmq/producer/send_status.go
  plugins/rocketmq/producer/structures.go
  plugins/rocketmq/producer/sync_producer.go
  test/plugins/runner-helper/context.go
  test/plugins/runner-helper/templates/docker-compose.tpl
  test/plugins/scenarios/rocketmq/bin/startup.sh
  test/plugins/scenarios/rocketmq/config/broker.conf
  test/plugins/scenarios/rocketmq/config/excepted.yml
  test/plugins/scenarios/rocketmq/go.mod
  test/plugins/scenarios/rocketmq/go.sum
  test/plugins/scenarios/rocketmq/main.go
  test/plugins/scenarios/rocketmq/plugin.yml
  tools/go-agent/instrument/plugins/register.go
Labels: plugin

#165 feature: add support for AMQP
  .github/workflows/plugin-tests.yaml
  CHANGES.md
  docs/en/agent/support-plugins.md
  go.work
  plugins/amqp/consumer.go
  plugins/amqp/consumer_with_ctx.go
  plugins/amqp/dial_hook.go
  plugins/amqp/general_consumer.go
  plugins/amqp/go.mod
  plugins/amqp/go.sum
  plugins/amqp/instrument.go
  plugins/amqp/producer.go
  plugins/amqp/structures.go
  test/plugins/scenarios/amqp/bin/startup.sh
  test/plugins/scenarios/amqp/config/excepted.yml
  test/plugins/scenarios/amqp/go.mod
  test/plugins/scenarios/amqp/go.sum
  test/plugins/scenarios/amqp/main.go
  test/plugins/scenarios/amqp/plugin.yml
  tools/go-agent/instrument/plugins/register.go
  tools/go-agent/tools/dst.go
  tools/go-agent/tools/enhancement.go
Labels: enhancement

#168 fix sql instrument with DBQueryContext
  CHANGES.md
  plugins/sql/entry/span.go
Labels: bug

#171 Update Changes for ready release 0.4.0
  CHANGES.md
Labels: chore

#172 Update NOTICE to 2024
  NOTICE
  dist/NOTICE
Labels: documentation
