Repository apache/skywalking-go, pull requests merged in 2024-01, with the labels that each got.

#158 feature: add support for echov4
  .github/workflows/plugin-tests.yaml
  CHANGES.md
  docs/en/agent/support-plugins.md
  go.work
  go.work.sum
  plugins/echov4/go.mod
  plugins/echov4/go.sum
  plugins/echov4/instrument.go
  plugins/echov4/intercepter.go
  test/plugins/Makefile
  test/plugins/scenarios/echov4/bin/startup.sh
  test/plugins/scenarios/echov4/config/excepted.yml
  test/plugins/scenarios/echov4/go.mod
  test/plugins/scenarios/echov4/go.sum
  test/plugins/scenarios/echov4/main.go
  test/plugins/scenarios/echov4/plugin.yml
  tools/go-agent/instrument/plugins/register.go
Labels: plugin

#159 fix special case for ParseVendorModule
  .gitignore
  CHANGES.md
  tools/go-agent/tools/testdata/special-modules.txt
  tools/go-agent/tools/vendor.go
  tools/go-agent/tools/vendor_test.go
Labels: bug

#160 Fix enhance method error when unknown parameter type
  CHANGES.md
  tools/go-agent/instrument/plugins/templates/method_intercept_after.tmpl
  tools/go-agent/instrument/plugins/templates/method_intercept_before.tmpl
  tools/go-agent/tools/enhancement.go
  tools/go-agent/tools/enhancement_test.go
Labels: bug

#161 Fix wrong tracing context when trace have been sampled
  CHANGES.md
  plugins/core/span_noop.go
  plugins/core/span_tracing.go
  plugins/core/tracing.go
  plugins/core/tracing_test.go
Labels: bug

#162 Fix enhance param error when there are multiple params
  CHANGES.md
  tools/go-agent/tools/enhancement.go
  tools/go-agent/tools/enhancement_test.go
Labels: enhancement

#163 Add support ignore suffix
  CHANGES.md
  docs/en/agent/tracing-metrics-logging.md
  plugins/core/tracer.go
  plugins/core/tracing.go
  tools/go-agent/config/agent.default.yaml
  tools/go-agent/config/loader.go
  tools/go-agent/instrument/agentcore/instrument.go
Labels: enhancement
