Repository apache/skywalking-go, pull requests merged in 2024-08, with the labels that each got.

#191 Fixing missing `docker-compose` command
  .github/workflows/plugin-tests.yaml
Labels: chore

#190 fix: when not route is found, the gin operation name is "http.Method:", example: "GET:".
  CHANGES.md
  plugins/gin/intercepter.go
  plugins/gin/intercepter_test.go
  test/plugins/scenarios/gin/config/excepted.yml
  test/plugins/scenarios/gin/main.go
Labels: enhancement, plugin

#192 Support enhancement with go 1.23
  CHANGES.md
  test/plugins/scenarios/gin/plugin.yml
  test/plugins/scenarios/http/plugin.yml
  test/plugins/scenarios/trace-activation/plugin.yml
  tools/go-agent/instrument/api/flags.go
  tools/go-agent/instrument/runtime/instrument.go
Labels: enhancement

#193 Fix got `span type is wrong` error when creating exit span with trace sampling
  CHANGES.md
  plugins/core/tracing.go
Labels: bug

#196 Add generated VERSION file into license ignoring list.
  .licenserc.yaml
Labels: documentation

#195 Remove wrong link in vote mail from how-to-release doc
  docs/en/development-and-contribution/how-to-release.md
Labels: documentation

#197 Begin 0.6.0 milestone
  CHANGES.md
Labels: chore

#199 Fix wrong docker image name and `-version` command
  CHANGES.md
  Makefile
  tools/go-agent/Makefile
  tools/go-agent/cmd/helper.go
Labels: bug
