Repository apache/skywalking-go, pull requests merged in 2024-04, with the labels that each got.

#180 chore: enhance makefile
  CHANGES.md
  Makefile
Labels: enhancement

#181 chore: reduce the duration and make more stable for plugin test
  .github/workflows/plugin-tests.yaml
  go.work
  go.work.sum
  test/plugins/scenarios/kratosv2/main.go
  test/plugins/scenarios/short_versions_gin/bin/startup.sh
  test/plugins/scenarios/short_versions_gin/config/excepted.yml
  test/plugins/scenarios/short_versions_gin/go.mod
  test/plugins/scenarios/short_versions_gin/go.sum
  test/plugins/scenarios/short_versions_gin/main.go
  test/plugins/scenarios/short_versions_gin/plugin.yml
Labels: chore

#179 fix: hybird compilation issue on windows
  tools/go-agent/instrument/agentcore/instrument.go
  tools/go-agent/instrument/instrument.go
  tools/go-agent/instrument/plugins/instrument.go
  tools/go-agent/instrument/plugins/rewrite/import.go
  tools/go-agent/instrument/reporter/instrument.go
  tools/go-agent/tools/copy.go
  tools/go-agent/tools/dst.go
Labels: bug
