Repository apache/skywalking-go, pull requests merged in 2024-09, with the labels that each got.

#201 Fix redis plugin cannot work in cluster mode
  CHANGES.md
  plugins/go-redisv9/hook.go
Labels: bug

#204 Bump up actions/upload-artifact and actions/download-artifact to v4
  .github/workflows/plugin-tests.yaml
  .github/workflows/skywalking-go.yaml
Labels: chore

#206 docs: add toolkit docs
  CHANGES.md
  docs/en/advanced-features/manual-apis/toolkit-log.md
  docs/en/advanced-features/manual-apis/toolkit-metric.md
  docs/en/advanced-features/manual-apis/toolkit-trace.md
  docs/menu.yml
Labels: documentation
