Repository apache/skywalking-go, pull requests merged in 2024-06, with the labels that each got.

#185 feat: enhance version info
  .gitignore
  Makefile
  tools/go-agent/Makefile
  tools/go-agent/cmd/helper.go
  tools/release/create_source_release.sh
Labels: enhancement

#187 Resolve panic when root span finish
  CHANGES.md
  plugins/core/span_tracing.go
  plugins/core/tracing/api.go
Labels: bug

#186 Add support for go-elasticsearch
  .github/workflows/plugin-tests.yaml
  CHANGES.md
  docs/en/agent/support-plugins.md
  go.work
  plugins/core/tracer_ignore.go
  plugins/go-elasticsearchv8/go.mod
  plugins/go-elasticsearchv8/go.sum
  plugins/go-elasticsearchv8/instrument.go
  plugins/go-elasticsearchv8/intercepter.go
  test/plugins/scenarios/amqp/config/excepted.yml
  test/plugins/scenarios/amqp/main.go
  test/plugins/scenarios/go-elasticsearchv8/bin/startup.sh
  test/plugins/scenarios/go-elasticsearchv8/config/elasticsearch.yml
  test/plugins/scenarios/go-elasticsearchv8/config/excepted.yml
  test/plugins/scenarios/go-elasticsearchv8/go.mod
  test/plugins/scenarios/go-elasticsearchv8/go.sum
  test/plugins/scenarios/go-elasticsearchv8/main.go
  test/plugins/scenarios/go-elasticsearchv8/plugin.yml
  test/plugins/scenarios/grpc/config/excepted.yml
  test/plugins/scenarios/rocketmq/config/excepted.yml
  test/plugins/scenarios/trace-activation/config/excepted.yml
  tools/go-agent/instrument/plugins/register.go
  tools/go-agent/instrument/plugins/templates/method_intercept_after.tmpl
Labels: plugin
