Repository apache/skywalking-go, pull requests merged in 2025-04, with the labels that each got.

#217 [bugfix] Trace API continue context throw nil err
  plugins/toolkit-activation/trace/continue_intercepter.go
Labels: bug, enhancement

#218 Refactor: Replace emptyReporter with DiscardReporter
  plugins/core/reporter/discard_reporter.go
  plugins/core/reporter/discard_reporter_test.go
  plugins/core/tracer.go
Labels: enhancement

#220 Begin v0.7.0
  CHANGES.md
Labels: chore

#222 feat(ci): add GitHub Actions plugin test workflow for Windows
  .github/workflows/windows-plugin-test.yaml
Labels: testing
